### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by ILysvincent** [ros-drivers/wifi_ddwrt#4]
Hi there,

I ran the ddwrt.py, monitor and analysis node. Both monitor and ddwrt.py works perfectly. However the analysis node wouldn't run and it gives out such error as stated below:

mig-ly@cob3-3-pc1:~$ rosrun wifi_ddwrt analysis 
Requesting the static map
Traceback (most recent call last):
  File "/u/mig-ly/git/care-o-bot_catkin/src/wifi_ddwrt/scripts/analysis", line 209, in <module>
    analysis()

  File "/u/mig-ly/git/care-o-bot_catkin/src/wifi_ddwrt/scripts/analysis", line 204, in analysis
    wa = WifiAnalysis(listener)

 File "/u/mig-ly/git/care-o-bot_catkin/src/wifi_ddwrt/scripts/analysis", line 75, in **init**
    self.get_map()

  File "/u/mig-ly/git/care-o-bot_catkin/src/wifi_ddwrt/scripts/analysis", line 94, in get_map
    self.im = Image.frombuffer('L', size, resp.map.data, "raw", 'L', 0, 1)

  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1853, in frombuffer
    core.map_buffer(data, size, decoder_name, None, 0, args)

TypeError: expected string or buffer

Does anyone have any idea? @ahendrix . Thanks in advance.

**Comment by trainman419** [comment]
You've closed this; does that mean it's resolved?
